# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: revocation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'revocation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10revocation.proto\x12 accelbyte.platform.revocation.v1\"\xb9\x02\n\rRevokeRequest\x12\x17\n\x0frevokeEntryType\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x11\n\tnamespace\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12@\n\x04item\x18\x05 \x01(\x0b\x32\x32.accelbyte.platform.revocation.v1.RevokeItemObject\x12N\n\x0b\x65ntitlement\x18\x06 \x01(\x0b\x32\x39.accelbyte.platform.revocation.v1.RevokeEntitlementObject\x12H\n\x08\x63urrency\x18\x07 \x01(\x0b\x32\x36.accelbyte.platform.revocation.v1.RevokeCurrencyObject\"\xcb\x01\n\x0eRevokeResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12`\n\x10\x63ustomRevocation\x18\x03 \x03(\x0b\x32\x46.accelbyte.platform.revocation.v1.RevokeResponse.CustomRevocationEntry\x1a\x37\n\x15\x43ustomRevocationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"p\n\x10RevokeItemObject\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\x0f\n\x07itemSku\x18\x02 \x01(\t\x12\x10\n\x08itemType\x18\x03 \x01(\t\x12\x10\n\x08useCount\x18\x04 \x01(\x05\x12\x17\n\x0f\x65ntitlementType\x18\x05 \x01(\t\"M\n\x17RevokeEntitlementObject\x12\x15\n\rentitlementId\x18\x01 \x01(\t\x12\x0e\n\x06itemId\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\"V\n\x14RevokeCurrencyObject\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrencyCode\x18\x02 \x01(\t\x12\x15\n\rbalanceOrigin\x18\x03 \x01(\t2y\n\nRevocation\x12k\n\x06Revoke\x12/.accelbyte.platform.revocation.v1.RevokeRequest\x1a\x30.accelbyte.platform.revocation.v1.RevokeResponseB\x82\x01\n$net.accelbyte.platform.revocation.v1B\x0frevocationProtoP\x01Z$accelbyte.net/platform/revocation_v1\xaa\x02 Accelbyte.Platform.revocation.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'revocation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$net.accelbyte.platform.revocation.v1B\017revocationProtoP\001Z$accelbyte.net/platform/revocation_v1\252\002 Accelbyte.Platform.revocation.V1'
  _globals['_REVOKERESPONSE_CUSTOMREVOCATIONENTRY']._loaded_options = None
  _globals['_REVOKERESPONSE_CUSTOMREVOCATIONENTRY']._serialized_options = b'8\001'
  _globals['_REVOKEREQUEST']._serialized_start=55
  _globals['_REVOKEREQUEST']._serialized_end=368
  _globals['_REVOKERESPONSE']._serialized_start=371
  _globals['_REVOKERESPONSE']._serialized_end=574
  _globals['_REVOKERESPONSE_CUSTOMREVOCATIONENTRY']._serialized_start=519
  _globals['_REVOKERESPONSE_CUSTOMREVOCATIONENTRY']._serialized_end=574
  _globals['_REVOKEITEMOBJECT']._serialized_start=576
  _globals['_REVOKEITEMOBJECT']._serialized_end=688
  _globals['_REVOKEENTITLEMENTOBJECT']._serialized_start=690
  _globals['_REVOKEENTITLEMENTOBJECT']._serialized_end=767
  _globals['_REVOKECURRENCYOBJECT']._serialized_start=769
  _globals['_REVOKECURRENCYOBJECT']._serialized_end=855
  _globals['_REVOCATION']._serialized_start=857
  _globals['_REVOCATION']._serialized_end=978
# @@protoc_insertion_point(module_scope)
