# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/revocation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/proto/revocation.proto',
  package='accelbyte.platform.revocation.v1',
  syntax='proto3',
  serialized_options=b'\n$net.accelbyte.platform.revocation.v1B\017revocationProtoP\001Z$accelbyte.net/platform/revocation_v1\252\002 Accelbyte.Platform.revocation.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x61pp/proto/revocation.proto\x12 accelbyte.platform.revocation.v1\"\xb9\x02\n\rRevokeRequest\x12\x17\n\x0frevokeEntryType\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x11\n\tnamespace\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12@\n\x04item\x18\x05 \x01(\x0b\x32\x32.accelbyte.platform.revocation.v1.RevokeItemObject\x12N\n\x0b\x65ntitlement\x18\x06 \x01(\x0b\x32\x39.accelbyte.platform.revocation.v1.RevokeEntitlementObject\x12H\n\x08\x63urrency\x18\x07 \x01(\x0b\x32\x36.accelbyte.platform.revocation.v1.RevokeCurrencyObject\"\xcb\x01\n\x0eRevokeResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12`\n\x10\x63ustomRevocation\x18\x03 \x03(\x0b\x32\x46.accelbyte.platform.revocation.v1.RevokeResponse.CustomRevocationEntry\x1a\x37\n\x15\x43ustomRevocationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"p\n\x10RevokeItemObject\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\x0f\n\x07itemSku\x18\x02 \x01(\t\x12\x10\n\x08itemType\x18\x03 \x01(\t\x12\x10\n\x08useCount\x18\x04 \x01(\x05\x12\x17\n\x0f\x65ntitlementType\x18\x05 \x01(\t\"M\n\x17RevokeEntitlementObject\x12\x15\n\rentitlementId\x18\x01 \x01(\t\x12\x0e\n\x06itemId\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\"V\n\x14RevokeCurrencyObject\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrencyCode\x18\x02 \x01(\t\x12\x15\n\rbalanceOrigin\x18\x03 \x01(\t2y\n\nRevocation\x12k\n\x06Revoke\x12/.accelbyte.platform.revocation.v1.RevokeRequest\x1a\x30.accelbyte.platform.revocation.v1.RevokeResponseB\x82\x01\n$net.accelbyte.platform.revocation.v1B\x0frevocationProtoP\x01Z$accelbyte.net/platform/revocation_v1\xaa\x02 Accelbyte.Platform.revocation.V1b\x06proto3'
)




_REVOKEREQUEST = _descriptor.Descriptor(
  name='RevokeRequest',
  full_name='accelbyte.platform.revocation.v1.RevokeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='revokeEntryType', full_name='accelbyte.platform.revocation.v1.RevokeRequest.revokeEntryType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='accelbyte.platform.revocation.v1.RevokeRequest.userId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='accelbyte.platform.revocation.v1.RevokeRequest.namespace', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='accelbyte.platform.revocation.v1.RevokeRequest.quantity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item', full_name='accelbyte.platform.revocation.v1.RevokeRequest.item', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entitlement', full_name='accelbyte.platform.revocation.v1.RevokeRequest.entitlement', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currency', full_name='accelbyte.platform.revocation.v1.RevokeRequest.currency', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=378,
)


_REVOKERESPONSE_CUSTOMREVOCATIONENTRY = _descriptor.Descriptor(
  name='CustomRevocationEntry',
  full_name='accelbyte.platform.revocation.v1.RevokeResponse.CustomRevocationEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='accelbyte.platform.revocation.v1.RevokeResponse.CustomRevocationEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='accelbyte.platform.revocation.v1.RevokeResponse.CustomRevocationEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=584,
)

_REVOKERESPONSE = _descriptor.Descriptor(
  name='RevokeResponse',
  full_name='accelbyte.platform.revocation.v1.RevokeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='accelbyte.platform.revocation.v1.RevokeResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='accelbyte.platform.revocation.v1.RevokeResponse.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='customRevocation', full_name='accelbyte.platform.revocation.v1.RevokeResponse.customRevocation', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REVOKERESPONSE_CUSTOMREVOCATIONENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=584,
)


_REVOKEITEMOBJECT = _descriptor.Descriptor(
  name='RevokeItemObject',
  full_name='accelbyte.platform.revocation.v1.RevokeItemObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemId', full_name='accelbyte.platform.revocation.v1.RevokeItemObject.itemId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemSku', full_name='accelbyte.platform.revocation.v1.RevokeItemObject.itemSku', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemType', full_name='accelbyte.platform.revocation.v1.RevokeItemObject.itemType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='useCount', full_name='accelbyte.platform.revocation.v1.RevokeItemObject.useCount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entitlementType', full_name='accelbyte.platform.revocation.v1.RevokeItemObject.entitlementType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=586,
  serialized_end=698,
)


_REVOKEENTITLEMENTOBJECT = _descriptor.Descriptor(
  name='RevokeEntitlementObject',
  full_name='accelbyte.platform.revocation.v1.RevokeEntitlementObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entitlementId', full_name='accelbyte.platform.revocation.v1.RevokeEntitlementObject.entitlementId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemId', full_name='accelbyte.platform.revocation.v1.RevokeEntitlementObject.itemId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sku', full_name='accelbyte.platform.revocation.v1.RevokeEntitlementObject.sku', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=700,
  serialized_end=777,
)


_REVOKECURRENCYOBJECT = _descriptor.Descriptor(
  name='RevokeCurrencyObject',
  full_name='accelbyte.platform.revocation.v1.RevokeCurrencyObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='accelbyte.platform.revocation.v1.RevokeCurrencyObject.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currencyCode', full_name='accelbyte.platform.revocation.v1.RevokeCurrencyObject.currencyCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='balanceOrigin', full_name='accelbyte.platform.revocation.v1.RevokeCurrencyObject.balanceOrigin', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=779,
  serialized_end=865,
)

_REVOKEREQUEST.fields_by_name['item'].message_type = _REVOKEITEMOBJECT
_REVOKEREQUEST.fields_by_name['entitlement'].message_type = _REVOKEENTITLEMENTOBJECT
_REVOKEREQUEST.fields_by_name['currency'].message_type = _REVOKECURRENCYOBJECT
_REVOKERESPONSE_CUSTOMREVOCATIONENTRY.containing_type = _REVOKERESPONSE
_REVOKERESPONSE.fields_by_name['customRevocation'].message_type = _REVOKERESPONSE_CUSTOMREVOCATIONENTRY
DESCRIPTOR.message_types_by_name['RevokeRequest'] = _REVOKEREQUEST
DESCRIPTOR.message_types_by_name['RevokeResponse'] = _REVOKERESPONSE
DESCRIPTOR.message_types_by_name['RevokeItemObject'] = _REVOKEITEMOBJECT
DESCRIPTOR.message_types_by_name['RevokeEntitlementObject'] = _REVOKEENTITLEMENTOBJECT
DESCRIPTOR.message_types_by_name['RevokeCurrencyObject'] = _REVOKECURRENCYOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RevokeRequest = _reflection.GeneratedProtocolMessageType('RevokeRequest', (_message.Message,), {
  'DESCRIPTOR' : _REVOKEREQUEST,
  '__module__' : 'app.proto.revocation_pb2'
  # @@protoc_insertion_point(class_scope:accelbyte.platform.revocation.v1.RevokeRequest)
  })
_sym_db.RegisterMessage(RevokeRequest)

RevokeResponse = _reflection.GeneratedProtocolMessageType('RevokeResponse', (_message.Message,), {

  'CustomRevocationEntry' : _reflection.GeneratedProtocolMessageType('CustomRevocationEntry', (_message.Message,), {
    'DESCRIPTOR' : _REVOKERESPONSE_CUSTOMREVOCATIONENTRY,
    '__module__' : 'app.proto.revocation_pb2'
    # @@protoc_insertion_point(class_scope:accelbyte.platform.revocation.v1.RevokeResponse.CustomRevocationEntry)
    })
  ,
  'DESCRIPTOR' : _REVOKERESPONSE,
  '__module__' : 'app.proto.revocation_pb2'
  # @@protoc_insertion_point(class_scope:accelbyte.platform.revocation.v1.RevokeResponse)
  })
_sym_db.RegisterMessage(RevokeResponse)
_sym_db.RegisterMessage(RevokeResponse.CustomRevocationEntry)

RevokeItemObject = _reflection.GeneratedProtocolMessageType('RevokeItemObject', (_message.Message,), {
  'DESCRIPTOR' : _REVOKEITEMOBJECT,
  '__module__' : 'app.proto.revocation_pb2'
  # @@protoc_insertion_point(class_scope:accelbyte.platform.revocation.v1.RevokeItemObject)
  })
_sym_db.RegisterMessage(RevokeItemObject)

RevokeEntitlementObject = _reflection.GeneratedProtocolMessageType('RevokeEntitlementObject', (_message.Message,), {
  'DESCRIPTOR' : _REVOKEENTITLEMENTOBJECT,
  '__module__' : 'app.proto.revocation_pb2'
  # @@protoc_insertion_point(class_scope:accelbyte.platform.revocation.v1.RevokeEntitlementObject)
  })
_sym_db.RegisterMessage(RevokeEntitlementObject)

RevokeCurrencyObject = _reflection.GeneratedProtocolMessageType('RevokeCurrencyObject', (_message.Message,), {
  'DESCRIPTOR' : _REVOKECURRENCYOBJECT,
  '__module__' : 'app.proto.revocation_pb2'
  # @@protoc_insertion_point(class_scope:accelbyte.platform.revocation.v1.RevokeCurrencyObject)
  })
_sym_db.RegisterMessage(RevokeCurrencyObject)


DESCRIPTOR._options = None
_REVOKERESPONSE_CUSTOMREVOCATIONENTRY._options = None

_REVOCATION = _descriptor.ServiceDescriptor(
  name='Revocation',
  full_name='accelbyte.platform.revocation.v1.Revocation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=867,
  serialized_end=988,
  methods=[
  _descriptor.MethodDescriptor(
    name='Revoke',
    full_name='accelbyte.platform.revocation.v1.Revocation.Revoke',
    index=0,
    containing_service=None,
    input_type=_REVOKEREQUEST,
    output_type=_REVOKERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REVOCATION)

DESCRIPTOR.services_by_name['Revocation'] = _REVOCATION

# @@protoc_insertion_point(module_scope)
